services:
  - type: web
    name: hydraulics
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ug.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
